version: '3.8'

services:
  workspace:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      APP_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    tty: true
    networks:
      - main

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - main

networks:
  main:
