version: '3.8'

services:
  workspace:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:80"
    tty: true
    networks:
      - main

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - main

networks:
  main:
